export type MaterialStats = {
  name: string;
  crystalSystem: string;
  spaceGroup: string;
  latticeParams: string;
  modulus: string;
  poisson: string;
  hardness: string;
  composition: { name: string; value: number; fill: string }[];
  morphology: string;
  defectAnalysis: string;
  spectrumShift: number; 
};

export const materialDatabase: MaterialStats[] = [
  {
    name: "Aluminum (Al)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 4.049 Å",
    modulus: "69 GPa",
    poisson: "0.33",
    hardness: "2.75 Mohs",
    composition: [
      { name: "Al", value: 97, fill: "#9ca3af" },
      { name: "O", value: 2.5, fill: "#06b6d4" },
      { name: "Mg", value: 0.5, fill: "#3b82f6" },
    ],
    morphology: "Smooth metallic surface with thin native oxide layer (Al2O3). Grain boundaries are well-defined with occasional etch pits.",
    defectAnalysis: "Low dislocation density. Minor oxide inclusions present at grain interfaces.",
    spectrumShift: 10
  },
  {
    name: "Copper (Cu)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 3.615 Å",
    modulus: "110–128 GPa",
    poisson: "0.34",
    hardness: "3 Mohs",
    composition: [
      { name: "Cu", value: 98, fill: "#ea580c" },
      { name: "O", value: 1.5, fill: "#06b6d4" },
      { name: "Zn", value: 0.5, fill: "#a855f7" },
    ],
    morphology: "Polycrystalline grains with visible slip bands indicating plastic deformation.",
    defectAnalysis: "Dense dislocation network with annealing twins present.",
    spectrumShift: -5
  },
  {
    name: "Nickel (Ni)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 3.524 Å",
    modulus: "200 GPa",
    poisson: "0.31",
    hardness: "4 Mohs",
    composition: [
      { name: "Ni", value: 99, fill: "#6b7280" },
      { name: "Fe", value: 0.7, fill: "#94a3b8" },
      { name: "C", value: 0.3, fill: "#3b82f6" },
    ],
    morphology: "Uniform metallic grains with high reflectivity and minimal oxidation.",
    defectAnalysis: "Moderate dislocation density with occasional twin boundaries.",
    spectrumShift: -8
  },
  {
    name: "Silver (Ag)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 4.085 Å",
    modulus: "83 GPa",
    poisson: "0.37",
    hardness: "2.5 Mohs",
    composition: [
      { name: "Ag", value: 99.2, fill: "#e5e7eb" },
      { name: "O", value: 0.5, fill: "#06b6d4" },
      { name: "Cu", value: 0.3, fill: "#f59e0b" },
    ],
    morphology: "Bright metallic surface with smooth grain boundaries.",
    defectAnalysis: "Extensive twinning due to high ductility.",
    spectrumShift: -25
  },
  {
    name: "Gold (Au)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 4.078 Å",
    modulus: "79 GPa",
    poisson: "0.44",
    hardness: "2.5 Mohs",
    composition: [
      { name: "Au", value: 99.5, fill: "#eab308" },
      { name: "Ag", value: 0.3, fill: "#e5e7eb" },
      { name: "Cu", value: 0.2, fill: "#ea580c" },
    ],
    morphology: "Dense metallic grains with high surface smoothness.",
    defectAnalysis: "Frequent multiple twinning structures observed.",
    spectrumShift: -10
  },
  {
    name: "Iron (α-Fe)",
    crystalSystem: "Body-Centered Cubic (BCC)",
    spaceGroup: "Im-3m",
    latticeParams: "a = 2.866 Å",
    modulus: "200 GPa",
    poisson: "0.29",
    hardness: "4 Mohs",
    composition: [
      { name: "Fe", value: 97, fill: "#94a3b8" },
      { name: "C", value: 2, fill: "#3b82f6" },
      { name: "Mn", value: 1, fill: "#a855f7" },
    ],
    morphology: "Granular ferrite matrix with pearlite regions.",
    defectAnalysis: "High dislocation density due to cold work.",
    spectrumShift: 15
  },
  {
    name: "Chromium (Cr)",
    crystalSystem: "Body-Centered Cubic (BCC)",
    spaceGroup: "Im-3m",
    latticeParams: "a = 2.884 Å",
    modulus: "279 GPa",
    poisson: "0.21",
    hardness: "8.5 Mohs",
    composition: [
      { name: "Cr", value: 99, fill: "#9ca3af" },
      { name: "O", value: 1, fill: "#06b6d4" },
    ],
    morphology: "Hard crystalline surface with sharp grain edges.",
    defectAnalysis: "Low dislocation mobility due to brittleness.",
    spectrumShift: 12
  },
  {
    name: "Tungsten (W)",
    crystalSystem: "Body-Centered Cubic (BCC)",
    spaceGroup: "Im-3m",
    latticeParams: "a = 3.165 Å",
    modulus: "400 GPa",
    poisson: "0.28",
    hardness: "7.5 Mohs",
    composition: [
      { name: "W", value: 99.5, fill: "#6b7280" },
      { name: "C", value: 0.5, fill: "#3b82f6" },
    ],
    morphology: "Dense, compact grains with minimal porosity.",
    defectAnalysis: "Very low defect density, high thermal stability.",
    spectrumShift: 20
  },
  {
    name: "Titanium (Ti)",
    crystalSystem: "Hexagonal Close-Packed (HCP)",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 2.95 Å, c = 4.68 Å",
    modulus: "110 GPa",
    poisson: "0.32",
    hardness: "6 Mohs",
    composition: [
      { name: "Ti", value: 90, fill: "#cbd5e1" },
      { name: "Al", value: 6, fill: "#9ca3af" },
      { name: "V", value: 4, fill: "#f59e0b" },
    ],
    morphology: "Widmanstätten structure with lamellar plates.",
    defectAnalysis: "Strong resistance to crack propagation.",
    spectrumShift: 35
  },
  {
    name: "Magnesium (Mg)",
    crystalSystem: "Hexagonal Close-Packed (HCP)",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 3.21 Å, c = 5.21 Å",
    modulus: "45 GPa",
    poisson: "0.29",
    hardness: "2.5 Mohs",
    composition: [
      { name: "Mg", value: 98, fill: "#d1d5db" },
      { name: "Al", value: 1.5, fill: "#9ca3af" },
      { name: "Zn", value: 0.5, fill: "#a855f7" },
    ],
    morphology: "Lightweight structure with coarse grains.",
    defectAnalysis: "High susceptibility to deformation twinning.",
    spectrumShift: 18
  },
  {
    name: "Zinc (Zn)",
    crystalSystem: "Hexagonal Close-Packed (HCP)",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 2.66 Å, c = 4.95 Å",
    modulus: "108 GPa",
    poisson: "0.25",
    hardness: "2.5 Mohs",
    composition: [
      { name: "Zn", value: 99, fill: "#9ca3af" },
      { name: "O", value: 1, fill: "#06b6d4" },
    ],
    morphology: "Layered hexagonal grains with moderate surface oxidation.",
    defectAnalysis: "Twinning prevalent due to HCP structure.",
    spectrumShift: 14
  },
  {
    name: "Lead (Pb)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 4.95 Å",
    modulus: "16 GPa",
    poisson: "0.44",
    hardness: "1.5 Mohs",
    composition: [
      { name: "Pb", value: 99.5, fill: "#6b7280" },
      { name: "Sn", value: 0.5, fill: "#9ca3af" },
    ],
    morphology: "Soft, ductile grains with smooth boundaries.",
    defectAnalysis: "High dislocation mobility due to softness.",
    spectrumShift: -12
  },
  {
    name: "Tin (Sn)",
    crystalSystem: "Tetragonal",
    spaceGroup: "I4_1/amd",
    latticeParams: "a = 5.83 Å, c = 3.18 Å",
    modulus: "50 GPa",
    poisson: "0.36",
    hardness: "1.5 Mohs",
    composition: [
      { name: "Sn", value: 99, fill: "#9ca3af" },
      { name: "Pb", value: 1, fill: "#6b7280" },
    ],
    morphology: "Layered structure with anisotropic grain growth.",
    defectAnalysis: "Moderate defect concentration along planes.",
    spectrumShift: 8
  },
  {
    name: "Cobalt (Co)",
    crystalSystem: "Hexagonal Close-Packed (HCP)",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 2.51 Å, c = 4.07 Å",
    modulus: "209 GPa",
    poisson: "0.31",
    hardness: "5 Mohs",
    composition: [
      { name: "Co", value: 98, fill: "#6b7280" },
      { name: "Fe", value: 2, fill: "#94a3b8" },
    ],
    morphology: "Dense grains with metallic luster.",
    defectAnalysis: "Low dislocation density, high magnetic domain alignment.",
    spectrumShift: 11
  },
  {
    name: "Platinum (Pt)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 3.92 Å",
    modulus: "168 GPa",
    poisson: "0.38",
    hardness: "4 Mohs",
    composition: [
      { name: "Pt", value: 99.5, fill: "#e5e7eb" },
      { name: "Ir", value: 0.5, fill: "#9ca3af" },
    ],
    morphology: "Compact grains with high density.",
    defectAnalysis: "Minimal defects, excellent stability.",
    spectrumShift: -6
  },
  {
    name: "Palladium (Pd)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 3.89 Å",
    modulus: "121 GPa",
    poisson: "0.39",
    hardness: "4.5 Mohs",
    composition: [
      { name: "Pd", value: 99, fill: "#d1d5db" },
      { name: "Pt", value: 1, fill: "#e5e7eb" },
    ],
    morphology: "Fine grains with smooth metallic surface.",
    defectAnalysis: "Hydrogen absorption may induce micro defects.",
    spectrumShift: -7
  },
  {
    name: "Nickel Alloy (Inconel)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a ≈ 3.59 Å",
    modulus: "200 GPa",
    poisson: "0.29",
    hardness: "5.5 Mohs",
    composition: [
      { name: "Ni", value: 70, fill: "#6b7280" },
      { name: "Cr", value: 20, fill: "#9ca3af" },
      { name: "Fe", value: 10, fill: "#94a3b8" },
    ],
    morphology: "Dense grain structure with precipitate strengthening.",
    defectAnalysis: "Carbide precipitates enhance strength.",
    spectrumShift: 22
  },
  {
    name: "Brass (Cu-Zn)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a ≈ 3.70 Å",
    modulus: "100 GPa",
    poisson: "0.34",
    hardness: "3 Mohs",
    composition: [
      { name: "Cu", value: 65, fill: "#ea580c" },
      { name: "Zn", value: 35, fill: "#9ca3af" },
    ],
    morphology: "Uniform alloy grains with smooth finish.",
    defectAnalysis: "Moderate dislocation density.",
    spectrumShift: -3
  },
  {
    name: "Bronze (Cu-Sn)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a ≈ 3.75 Å",
    modulus: "110 GPa",
    poisson: "0.34",
    hardness: "3.5 Mohs",
    composition: [
      { name: "Cu", value: 88, fill: "#ea580c" },
      { name: "Sn", value: 12, fill: "#9ca3af" },
    ],
    morphology: "Coarse grains with visible segregation zones.",
    defectAnalysis: "Minor phase separation observed.",
    spectrumShift: -2
  },
  {
    name: "Silicon Carbide (SiC)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3mc",
    latticeParams: "a = 3.08 Å, c = 15.12 Å",
    modulus: "450 GPa",
    poisson: "0.19",
    hardness: "9.5 Mohs",
    composition: [
      { name: "Si", value: 50, fill: "#a855f7" },
      { name: "C", value: 50, fill: "#3b82f6" },
    ],
    morphology: "Extremely hard crystalline grains.",
    defectAnalysis: "Very low defect density.",
    spectrumShift: 30
  },
  {
    name: "Aluminum Oxide (Al2O3)",
    crystalSystem: "Trigonal",
    spaceGroup: "R-3c",
    latticeParams: "a = 4.76 Å, c = 12.99 Å",
    modulus: "370 GPa",
    poisson: "0.22",
    hardness: "9 Mohs",
    composition: [
      { name: "Al", value: 53, fill: "#9ca3af" },
      { name: "O", value: 47, fill: "#06b6d4" },
    ],
    morphology: "Dense ceramic grains with sharp edges.",
    defectAnalysis: "Brittle fracture zones visible.",
    spectrumShift: 28
  },
  {
    name: "Zirconium Oxide (ZrO2)",
    crystalSystem: "Monoclinic",
    spaceGroup: "P2_1/c",
    latticeParams: "a = 5.15 Å",
    modulus: "200 GPa",
    poisson: "0.30",
    hardness: "8 Mohs",
    composition: [
      { name: "Zr", value: 74, fill: "#9ca3af" },
      { name: "O", value: 26, fill: "#06b6d4" },
    ],
    morphology: "Fine ceramic grains with transformation toughening.",
    defectAnalysis: "Phase transformation enhances toughness.",
    spectrumShift: 26
  },
  {
    name: "Silicon Nitride (Si3N4)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3/m",
    latticeParams: "a = 7.60 Å, c = 2.91 Å",
    modulus: "310 GPa",
    poisson: "0.27",
    hardness: "9 Mohs",
    composition: [
      { name: "Si", value: 60, fill: "#a855f7" },
      { name: "N", value: 40, fill: "#06b6d4" },
    ],
    morphology: "Interlocking elongated grains.",
    defectAnalysis: "High fracture resistance.",
    spectrumShift: 24
  },
  {
    name: "Diamond",
    crystalSystem: "Cubic",
    spaceGroup: "Fd-3m",
    latticeParams: "a = 3.567 Å",
    modulus: "1050 GPa",
    poisson: "0.10",
    hardness: "10 Mohs",
    composition: [
      { name: "C", value: 100, fill: "#3b82f6" },
    ],
    morphology: "Perfect crystalline lattice.",
    defectAnalysis: "Extremely low defect density.",
    spectrumShift: 40
  },
  {
    name: "Graphite",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 2.46 Å, c = 6.71 Å",
    modulus: "36 GPa",
    poisson: "0.16",
    hardness: "1–2 Mohs",
    composition: [
      { name: "C", value: 100, fill: "#3b82f6" },
    ],
    morphology: "Layered sheets with weak interlayer bonding.",
    defectAnalysis: "High anisotropy with interlayer defects.",
    spectrumShift: 5
  },
  {
    name: "Gallium Arsenide (GaAs)",
    crystalSystem: "Cubic",
    spaceGroup: "F-43m",
    latticeParams: "a = 5.653 Å",
    modulus: "85 GPa",
    poisson: "0.31",
    hardness: "5 Mohs",
    composition: [
      { name: "Ga", value: 50, fill: "#9ca3af" },
      { name: "As", value: 50, fill: "#ef4444" },
    ],
    morphology: "Smooth semiconductor surface.",
    defectAnalysis: "Low defect density.",
    spectrumShift: 32
  },
  {
    name: "Germanium (Ge)",
    crystalSystem: "Cubic (Diamond)",
    spaceGroup: "Fd-3m",
    latticeParams: "a = 5.658 Å",
    modulus: "103 GPa",
    poisson: "0.26",
    hardness: "6 Mohs",
    composition: [
      { name: "Ge", value: 100, fill: "#6b7280" },
    ],
    morphology: "Uniform crystalline structure.",
    defectAnalysis: "Low impurity levels.",
    spectrumShift: 31
  },
  {
    name: "Quartz (SiO2)",
    crystalSystem: "Trigonal",
    spaceGroup: "P3_121",
    latticeParams: "a = 4.91 Å, c = 5.40 Å",
    modulus: "70 GPa",
    poisson: "0.17",
    hardness: "7 Mohs",
    composition: [
      { name: "Si", value: 47, fill: "#a855f7" },
      { name: "O", value: 53, fill: "#06b6d4" },
    ],
    morphology: "Crystalline grains with fracture planes.",
    defectAnalysis: "Microcracks along cleavage planes.",
    spectrumShift: 18
  },
  {
    name: "Calcium Carbonate (CaCO3)",
    crystalSystem: "Trigonal",
    spaceGroup: "R-3c",
    latticeParams: "a = 4.99 Å, c = 17.06 Å",
    modulus: "72 GPa",
    poisson: "0.30",
    hardness: "3 Mohs",
    composition: [
      { name: "Ca", value: 40, fill: "#9ca3af" },
      { name: "C", value: 12, fill: "#3b82f6" },
      { name: "O", value: 48, fill: "#06b6d4" },
    ],
    morphology: "Granular crystalline aggregates.",
    defectAnalysis: "Porosity present.",
    spectrumShift: 12
  },
  {
    name: "Sodium Chloride (NaCl)",
    crystalSystem: "Cubic",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 5.64 Å",
    modulus: "25 GPa",
    poisson: "0.25",
    hardness: "2.5 Mohs",
    composition: [
      { name: "Na", value: 40, fill: "#3b82f6" },
      { name: "Cl", value: 60, fill: "#22c55e" },
    ],
    morphology: "Cubic crystals with smooth faces.",
    defectAnalysis: "Ionic vacancies present.",
    spectrumShift: 9
  },
  {
    name: "Polyethylene (PE)",
    crystalSystem: "Semi-Crystalline",
    spaceGroup: "—",
    latticeParams: "Amorphous + crystalline regions",
    modulus: "0.2 GPa",
    poisson: "0.45",
    hardness: "1 Mohs",
    composition: [
      { name: "C", value: 85, fill: "#3b82f6" },
      { name: "H", value: 15, fill: "#22c55e" },
    ],
    morphology: "Lamellar crystalline regions embedded in amorphous matrix.",
    defectAnalysis: "Chain entanglement defects dominate.",
    spectrumShift: 6
  },
  {
    name: "Polypropylene (PP)",
    crystalSystem: "Semi-Crystalline",
    spaceGroup: "—",
    latticeParams: "Amorphous/crystalline mix",
    modulus: "1.5 GPa",
    poisson: "0.42",
    hardness: "1.5 Mohs",
    composition: [
      { name: "C", value: 86, fill: "#3b82f6" },
      { name: "H", value: 14, fill: "#22c55e" },
    ],
    morphology: "Spherulitic structures with radial growth.",
    defectAnalysis: "Tacticity variations introduce structural defects.",
    spectrumShift: 7
  },
  {
    name: "Polystyrene (PS)",
    crystalSystem: "Amorphous",
    spaceGroup: "—",
    latticeParams: "Non-crystalline",
    modulus: "3 GPa",
    poisson: "0.35",
    hardness: "2 Mohs",
    composition: [
      { name: "C", value: 92, fill: "#3b82f6" },
      { name: "H", value: 8, fill: "#22c55e" },
    ],
    morphology: "Glassy amorphous surface.",
    defectAnalysis: "Void formation due to brittle fracture.",
    spectrumShift: 9
  },
  {
    name: "Polyvinyl Chloride (PVC)",
    crystalSystem: "Amorphous",
    spaceGroup: "—",
    latticeParams: "Non-crystalline",
    modulus: "3 GPa",
    poisson: "0.38",
    hardness: "2 Mohs",
    composition: [
      { name: "C", value: 38, fill: "#3b82f6" },
      { name: "H", value: 5, fill: "#22c55e" },
      { name: "Cl", value: 57, fill: "#22c55e" },
    ],
    morphology: "Smooth polymer matrix with minor inclusions.",
    defectAnalysis: "Plasticizer-induced defects possible.",
    spectrumShift: 8
  },
  {
    name: "Polytetrafluoroethylene (PTFE)",
    crystalSystem: "Semi-Crystalline",
    spaceGroup: "—",
    latticeParams: "Amorphous/crystalline mix",
    modulus: "0.5 GPa",
    poisson: "0.46",
    hardness: "1 Mohs",
    composition: [
      { name: "C", value: 24, fill: "#3b82f6" },
      { name: "F", value: 76, fill: "#22c55e" },
    ],
    morphology: "Highly smooth, low-friction surface.",
    defectAnalysis: "Minimal defects due to strong C-F bonds.",
    spectrumShift: 5
  },
  {
    name: "Epoxy Resin",
    crystalSystem: "Amorphous",
    spaceGroup: "—",
    latticeParams: "Cross-linked network",
    modulus: "3 GPa",
    poisson: "0.35",
    hardness: "2.5 Mohs",
    composition: [
      { name: "C", value: 70, fill: "#3b82f6" },
      { name: "O", value: 20, fill: "#06b6d4" },
      { name: "H", value: 10, fill: "#22c55e" },
    ],
    morphology: "Cross-linked rigid matrix.",
    defectAnalysis: "Microvoids present from curing.",
    spectrumShift: 11
  },
  {
    name: "Glass (Soda-Lime)",
    crystalSystem: "Amorphous",
    spaceGroup: "—",
    latticeParams: "Non-crystalline",
    modulus: "70 GPa",
    poisson: "0.23",
    hardness: "6 Mohs",
    composition: [
      { name: "SiO2", value: 70, fill: "#a855f7" },
      { name: "Na2O", value: 15, fill: "#3b82f6" },
      { name: "CaO", value: 15, fill: "#06b6d4" },
    ],
    morphology: "Smooth glassy surface.",
    defectAnalysis: "Microcracks and internal stresses.",
    spectrumShift: 14
  },
  {
    name: "Concrete",
    crystalSystem: "Composite",
    spaceGroup: "—",
    latticeParams: "Heterogeneous",
    modulus: "30 GPa",
    poisson: "0.2",
    hardness: "5 Mohs",
    composition: [
      { name: "Cement", value: 30, fill: "#9ca3af" },
      { name: "Sand", value: 40, fill: "#a855f7" },
      { name: "Aggregate", value: 30, fill: "#6b7280" },
    ],
    morphology: "Heterogeneous granular matrix.",
    defectAnalysis: "Porosity and microcracks prevalent.",
    spectrumShift: 13
  },
  {
    name: "Carbon Fiber",
    crystalSystem: "Graphitic",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a ≈ 2.46 Å",
    modulus: "230 GPa",
    poisson: "0.2",
    hardness: "7 Mohs",
    composition: [
      { name: "C", value: 95, fill: "#3b82f6" },
      { name: "Resin", value: 5, fill: "#22c55e" },
    ],
    morphology: "Aligned fibrous structure.",
    defectAnalysis: "Fiber-matrix interface defects.",
    spectrumShift: 19
  },
  {
    name: "Kevlar",
    crystalSystem: "Polymeric",
    spaceGroup: "—",
    latticeParams: "Chain aligned",
    modulus: "130 GPa",
    poisson: "0.36",
    hardness: "3 Mohs",
    composition: [
      { name: "C", value: 70, fill: "#3b82f6" },
      { name: "H", value: 5, fill: "#22c55e" },
      { name: "N", value: 25, fill: "#06b6d4" },
    ],
    morphology: "Highly aligned polymer chains.",
    defectAnalysis: "Chain misalignment defects.",
    spectrumShift: 17
  },
  {
    name: "Silicone Rubber",
    crystalSystem: "Amorphous",
    spaceGroup: "—",
    latticeParams: "Flexible chains",
    modulus: "0.01 GPa",
    poisson: "0.49",
    hardness: "0.5 Mohs",
    composition: [
      { name: "Si", value: 40, fill: "#a855f7" },
      { name: "O", value: 40, fill: "#06b6d4" },
      { name: "C", value: 20, fill: "#3b82f6" },
    ],
    morphology: "Highly flexible polymer network.",
    defectAnalysis: "Elastic deformation dominates.",
    spectrumShift: 4
  },
  {
    name: "Graphene Oxide",
    crystalSystem: "Layered",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a ≈ 2.46 Å",
    modulus: "200 GPa",
    poisson: "0.18",
    hardness: "5 Mohs",
    composition: [
      { name: "C", value: 80, fill: "#3b82f6" },
      { name: "O", value: 20, fill: "#06b6d4" },
    ],
    morphology: "Layered sheets with oxygen functional groups.",
    defectAnalysis: "High defect density due to oxidation.",
    spectrumShift: 23
  },
  {
    name: "Carbon Nanotubes (CNT)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a ≈ 2.46 Å",
    modulus: "1000 GPa",
    poisson: "0.19",
    hardness: "Extremely high",
    composition: [
      { name: "C", value: 99, fill: "#3b82f6" },
      { name: "Impurities", value: 1, fill: "#a855f7" },
    ],
    morphology: "Tubular nanostructures.",
    defectAnalysis: "Chirality defects present.",
    spectrumShift: 34
  },
  {
    name: "Boron Carbide (B4C)",
    crystalSystem: "Rhombohedral",
    spaceGroup: "R-3m",
    latticeParams: "a = 5.16 Å",
    modulus: "450 GPa",
    poisson: "0.17",
    hardness: "9.5 Mohs",
    composition: [
      { name: "B", value: 78, fill: "#f59e0b" },
      { name: "C", value: 22, fill: "#3b82f6" },
    ],
    morphology: "Hard ceramic grains.",
    defectAnalysis: "Brittle fracture zones.",
    spectrumShift: 29
  },
  {
    name: "Titanium Carbide (TiC)",
    crystalSystem: "Cubic",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 4.33 Å",
    modulus: "450 GPa",
    poisson: "0.19",
    hardness: "9 Mohs",
    composition: [
      { name: "Ti", value: 50, fill: "#cbd5e1" },
      { name: "C", value: 50, fill: "#3b82f6" },
    ],
    morphology: "Dense ceramic grains.",
    defectAnalysis: "Low defect density.",
    spectrumShift: 27
  },
  {
    name: "Zinc Oxide (ZnO)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3mc",
    latticeParams: "a = 3.25 Å, c = 5.21 Å",
    modulus: "140 GPa",
    poisson: "0.35",
    hardness: "4.5 Mohs",
    composition: [
      { name: "Zn", value: 50, fill: "#9ca3af" },
      { name: "O", value: 50, fill: "#06b6d4" },
    ],
    morphology: "Nanorod and hexagonal structures.",
    defectAnalysis: "Oxygen vacancies common.",
    spectrumShift: 21
  },
  {
    name: "Indium Tin Oxide (ITO)",
    crystalSystem: "Cubic",
    spaceGroup: "Ia-3",
    latticeParams: "a = 10.12 Å",
    modulus: "120 GPa",
    poisson: "0.35",
    hardness: "6 Mohs",
    composition: [
      { name: "In2O3", value: 90, fill: "#9ca3af" },
      { name: "SnO2", value: 10, fill: "#3b82f6" },
    ],
    morphology: "Transparent conductive film.",
    defectAnalysis: "Oxygen vacancies enhance conductivity.",
    spectrumShift: 25
  },
  {
    name: "Perovskite (CH3NH3PbI3)",
    crystalSystem: "Tetragonal",
    spaceGroup: "I4/mcm",
    latticeParams: "a = 8.85 Å",
    modulus: "20 GPa",
    poisson: "0.33",
    hardness: "2 Mohs",
    composition: [
      { name: "Pb", value: 30, fill: "#6b7280" },
      { name: "I", value: 50, fill: "#22c55e" },
      { name: "Organic", value: 20, fill: "#3b82f6" },
    ],
    morphology: "Polycrystalline thin films.",
    defectAnalysis: "High defect tolerance.",
    spectrumShift: 36
  },
  {
    name: "Molybdenum Disulfide (MoS2)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 3.16 Å, c = 12.3 Å",
    modulus: "270 GPa",
    poisson: "0.25",
    hardness: "1.5 Mohs",
    composition: [
      { name: "Mo", value: 60, fill: "#6b7280" },
      { name: "S", value: 40, fill: "#facc15" },
    ],
    morphology: "Layered sheets similar to graphite.",
    defectAnalysis: "Layer sliding defects.",
    spectrumShift: 22
  },
  {
    name: "Hydroxyapatite",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3/m",
    latticeParams: "a = 9.42 Å, c = 6.88 Å",
    modulus: "80 GPa",
    poisson: "0.27",
    hardness: "5 Mohs",
    composition: [
      { name: "Ca", value: 40, fill: "#9ca3af" },
      { name: "P", value: 18, fill: "#f59e0b" },
      { name: "O", value: 42, fill: "#06b6d4" },
    ],
    morphology: "Bone-like crystalline structure.",
    defectAnalysis: "Biocompatible defects.",
    spectrumShift: 16
  },
  {
    name: "Beryllium (Be)",
    crystalSystem: "Hexagonal Close-Packed (HCP)",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 2.29 Å, c = 3.58 Å",
    modulus: "287 GPa",
    poisson: "0.032",
    hardness: "5.5 Mohs",
    composition: [
      { name: "Be", value: 99, fill: "#9ca3af" },
      { name: "O", value: 1, fill: "#06b6d4" },
    ],
    morphology: "Fine grains with high stiffness.",
    defectAnalysis: "Low defect density, brittle fracture behavior.",
    spectrumShift: 18
  },
  {
    name: "Vanadium (V)",
    crystalSystem: "Body-Centered Cubic (BCC)",
    spaceGroup: "Im-3m",
    latticeParams: "a = 3.03 Å",
    modulus: "128 GPa",
    poisson: "0.37",
    hardness: "6 Mohs",
    composition: [
      { name: "V", value: 98, fill: "#6b7280" },
      { name: "O", value: 2, fill: "#06b6d4" },
    ],
    morphology: "Uniform metallic grains.",
    defectAnalysis: "Moderate dislocation density.",
    spectrumShift: 13
  },
  {
    name: "Niobium (Nb)",
    crystalSystem: "Body-Centered Cubic (BCC)",
    spaceGroup: "Im-3m",
    latticeParams: "a = 3.30 Å",
    modulus: "105 GPa",
    poisson: "0.40",
    hardness: "6 Mohs",
    composition: [
      { name: "Nb", value: 99, fill: "#9ca3af" },
      { name: "O", value: 1, fill: "#06b6d4" },
    ],
    morphology: "Ductile grains with smooth boundaries.",
    defectAnalysis: "Low dislocation density.",
    spectrumShift: 12
  },
  {
    name: "Molybdenum (Mo)",
    crystalSystem: "Body-Centered Cubic (BCC)",
    spaceGroup: "Im-3m",
    latticeParams: "a = 3.15 Å",
    modulus: "329 GPa",
    poisson: "0.31",
    hardness: "5.5 Mohs",
    composition: [
      { name: "Mo", value: 99, fill: "#6b7280" },
      { name: "C", value: 1, fill: "#3b82f6" },
    ],
    morphology: "Dense metallic grains with high thermal stability.",
    defectAnalysis: "Low defect density.",
    spectrumShift: 19
  },
  {
    name: "Rhenium (Re)",
    crystalSystem: "Hexagonal Close-Packed (HCP)",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 2.76 Å, c = 4.46 Å",
    modulus: "463 GPa",
    poisson: "0.30",
    hardness: "7 Mohs",
    composition: [
      { name: "Re", value: 99, fill: "#9ca3af" },
      { name: "O", value: 1, fill: "#06b6d4" },
    ],
    morphology: "Highly dense atomic packing.",
    defectAnalysis: "Minimal dislocations.",
    spectrumShift: 21
  },
  {
    name: "Osmium (Os)",
    crystalSystem: "Hexagonal Close-Packed (HCP)",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 2.73 Å, c = 4.32 Å",
    modulus: "550 GPa",
    poisson: "0.25",
    hardness: "7 Mohs",
    composition: [
      { name: "Os", value: 99, fill: "#6b7280" },
      { name: "Ir", value: 1, fill: "#9ca3af" },
    ],
    morphology: "Extremely dense crystalline structure.",
    defectAnalysis: "Very low defect density.",
    spectrumShift: 23
  },
  {
    name: "Iridium (Ir)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 3.84 Å",
    modulus: "528 GPa",
    poisson: "0.26",
    hardness: "6.5 Mohs",
    composition: [
      { name: "Ir", value: 99, fill: "#9ca3af" },
      { name: "Pt", value: 1, fill: "#e5e7eb" },
    ],
    morphology: "Highly dense metallic grains.",
    defectAnalysis: "Extremely low defect concentration.",
    spectrumShift: 20
  },
  {
    name: "Ruthenium (Ru)",
    crystalSystem: "Hexagonal Close-Packed (HCP)",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 2.71 Å, c = 4.28 Å",
    modulus: "447 GPa",
    poisson: "0.30",
    hardness: "6.5 Mohs",
    composition: [
      { name: "Ru", value: 99, fill: "#6b7280" },
      { name: "O", value: 1, fill: "#06b6d4" },
    ],
    morphology: "Fine dense grains.",
    defectAnalysis: "Low dislocation density.",
    spectrumShift: 18
  },
  {
    name: "Hafnium (Hf)",
    crystalSystem: "Hexagonal Close-Packed (HCP)",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 3.19 Å, c = 5.05 Å",
    modulus: "78 GPa",
    poisson: "0.37",
    hardness: "5.5 Mohs",
    composition: [
      { name: "Hf", value: 99, fill: "#9ca3af" },
      { name: "Zr", value: 1, fill: "#6b7280" },
    ],
    morphology: "Coarse grains with metallic luster.",
    defectAnalysis: "Moderate dislocation density.",
    spectrumShift: 17
  },
  {
    name: "Tantalum (Ta)",
    crystalSystem: "Body-Centered Cubic (BCC)",
    spaceGroup: "Im-3m",
    latticeParams: "a = 3.30 Å",
    modulus: "186 GPa",
    poisson: "0.34",
    hardness: "6 Mohs",
    composition: [
      { name: "Ta", value: 99, fill: "#9ca3af" },
      { name: "O", value: 1, fill: "#06b6d4" },
    ],
    morphology: "Ductile grains with smooth surface.",
    defectAnalysis: "Low dislocation density.",
    spectrumShift: 16
  },
  {
    name: "Uranium (U)",
    crystalSystem: "Orthorhombic",
    spaceGroup: "Cmcm",
    latticeParams: "a = 2.85 Å",
    modulus: "208 GPa",
    poisson: "0.23",
    hardness: "6 Mohs",
    composition: [
      { name: "U", value: 99, fill: "#84cc16" },
      { name: "O", value: 1, fill: "#06b6d4" },
    ],
    morphology: "Complex anisotropic grains.",
    defectAnalysis: "Radiation-induced defects.",
    spectrumShift: 35
  },
  {
    name: "Plutonium (Pu)",
    crystalSystem: "Monoclinic",
    spaceGroup: "P2_1/m",
    latticeParams: "a = 6.19 Å",
    modulus: "96 GPa",
    poisson: "0.21",
    hardness: "Unknown",
    composition: [
      { name: "Pu", value: 100, fill: "#84cc16" },
    ],
    morphology: "Highly complex crystal structure.",
    defectAnalysis: "Self-irradiation defects.",
    spectrumShift: 37
  },
  {
    name: "Lithium (Li)",
    crystalSystem: "Body-Centered Cubic (BCC)",
    spaceGroup: "Im-3m",
    latticeParams: "a = 3.51 Å",
    modulus: "4.9 GPa",
    poisson: "0.36",
    hardness: "0.6 Mohs",
    composition: [
      { name: "Li", value: 99, fill: "#a855f7" },
      { name: "O", value: 1, fill: "#06b6d4" },
    ],
    morphology: "Soft metallic surface.",
    defectAnalysis: "High diffusion-related defects.",
    spectrumShift: 10
  },
  {
    name: "Sodium (Na)",
    crystalSystem: "Body-Centered Cubic (BCC)",
    spaceGroup: "Im-3m",
    latticeParams: "a = 4.29 Å",
    modulus: "10 GPa",
    poisson: "0.35",
    hardness: "0.5 Mohs",
    composition: [
      { name: "Na", value: 99, fill: "#3b82f6" },
      { name: "O", value: 1, fill: "#06b6d4" },
    ],
    morphology: "Soft metallic lattice.",
    defectAnalysis: "High vacancy concentration.",
    spectrumShift: 9
  },
  {
    name: "Potassium (K)",
    crystalSystem: "Body-Centered Cubic (BCC)",
    spaceGroup: "Im-3m",
    latticeParams: "a = 5.23 Å",
    modulus: "3 GPa",
    poisson: "0.35",
    hardness: "0.4 Mohs",
    composition: [
      { name: "K", value: 99, fill: "#3b82f6" },
      { name: "O", value: 1, fill: "#06b6d4" },
    ],
    morphology: "Extremely soft metallic structure.",
    defectAnalysis: "High atomic mobility.",
    spectrumShift: 8
  },
  {
    name: "Cesium (Cs)",
    crystalSystem: "Body-Centered Cubic (BCC)",
    spaceGroup: "Im-3m",
    latticeParams: "a = 6.14 Å",
    modulus: "1.7 GPa",
    poisson: "0.35",
    hardness: "0.2 Mohs",
    composition: [
      { name: "Cs", value: 100, fill: "#3b82f6" },
    ],
    morphology: "Highly reactive soft metal.",
    defectAnalysis: "High vacancy formation.",
    spectrumShift: 7
  },
  {
    name: "Fluorite (CaF2)",
    crystalSystem: "Cubic",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 5.46 Å",
    modulus: "75 GPa",
    poisson: "0.26",
    hardness: "4 Mohs",
    composition: [
      { name: "Ca", value: 51, fill: "#9ca3af" },
      { name: "F", value: 49, fill: "#22c55e" },
    ],
    morphology: "Cubic crystals with cleavage planes.",
    defectAnalysis: "Fluorine vacancies present.",
    spectrumShift: 15
  },
  {
    name: "Magnetite (Fe3O4)",
    crystalSystem: "Cubic",
    spaceGroup: "Fd-3m",
    latticeParams: "a = 8.39 Å",
    modulus: "160 GPa",
    poisson: "0.29",
    hardness: "5.5 Mohs",
    composition: [
      { name: "Fe", value: 72, fill: "#94a3b8" },
      { name: "O", value: 28, fill: "#06b6d4" },
    ],
    morphology: "Granular magnetic particles.",
    defectAnalysis: "Cation vacancies present.",
    spectrumShift: 18
  },
  {
    name: "Hematite (Fe2O3)",
    crystalSystem: "Trigonal",
    spaceGroup: "R-3c",
    latticeParams: "a = 5.04 Å",
    modulus: "200 GPa",
    poisson: "0.28",
    hardness: "6 Mohs",
    composition: [
      { name: "Fe", value: 70, fill: "#94a3b8" },
      { name: "O", value: 30, fill: "#06b6d4" },
    ],
    morphology: "Layered oxide grains.",
    defectAnalysis: "Oxygen vacancies present.",
    spectrumShift: 17
  },
  {
    name: "Ilmenite (FeTiO3)",
    crystalSystem: "Trigonal",
    spaceGroup: "R-3",
    latticeParams: "a = 5.09 Å, c = 14.08 Å",
    modulus: "180 GPa",
    poisson: "0.27",
    hardness: "5–6 Mohs",
    composition: [
      { name: "Fe", value: 37, fill: "#94a3b8" },
      { name: "Ti", value: 32, fill: "#cbd5e1" },
      { name: "O", value: 31, fill: "#06b6d4" },
    ],
    morphology: "Layered oxide grains with metallic luster.",
    defectAnalysis: "Cation disorder and oxygen vacancies present.",
    spectrumShift: 18
  },
  {
    name: "Spinel (MgAl2O4)",
    crystalSystem: "Cubic",
    spaceGroup: "Fd-3m",
    latticeParams: "a = 8.08 Å",
    modulus: "200 GPa",
    poisson: "0.26",
    hardness: "8 Mohs",
    composition: [
      { name: "Mg", value: 17, fill: "#d1d5db" },
      { name: "Al", value: 37, fill: "#9ca3af" },
      { name: "O", value: 46, fill: "#06b6d4" },
    ],
    morphology: "Dense ceramic grains with high transparency.",
    defectAnalysis: "Anti-site defects observed.",
    spectrumShift: 22
  },
  {
    name: "Periclase (MgO)",
    crystalSystem: "Cubic",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 4.21 Å",
    modulus: "160 GPa",
    poisson: "0.18",
    hardness: "6 Mohs",
    composition: [
      { name: "Mg", value: 60, fill: "#d1d5db" },
      { name: "O", value: 40, fill: "#06b6d4" },
    ],
    morphology: "Cubic crystalline grains.",
    defectAnalysis: "Vacancy defects present.",
    spectrumShift: 14
  },
  {
    name: "Barium Titanate (BaTiO3)",
    crystalSystem: "Tetragonal",
    spaceGroup: "P4mm",
    latticeParams: "a = 3.99 Å, c = 4.03 Å",
    modulus: "120 GPa",
    poisson: "0.30",
    hardness: "5.5 Mohs",
    composition: [
      { name: "Ba", value: 45, fill: "#9ca3af" },
      { name: "Ti", value: 20, fill: "#cbd5e1" },
      { name: "O", value: 35, fill: "#06b6d4" },
    ],
    morphology: "Ferroelectric domains visible.",
    defectAnalysis: "Domain wall defects.",
    spectrumShift: 26
  },
  {
    name: "Strontium Titanate (SrTiO3)",
    crystalSystem: "Cubic",
    spaceGroup: "Pm-3m",
    latticeParams: "a = 3.91 Å",
    modulus: "105 GPa",
    poisson: "0.24",
    hardness: "6 Mohs",
    composition: [
      { name: "Sr", value: 48, fill: "#9ca3af" },
      { name: "Ti", value: 22, fill: "#cbd5e1" },
      { name: "O", value: 30, fill: "#06b6d4" },
    ],
    morphology: "Smooth crystalline grains.",
    defectAnalysis: "Oxygen vacancies affect conductivity.",
    spectrumShift: 24
  },
  {
    name: "Lead Zirconate Titanate (PZT)",
    crystalSystem: "Tetragonal",
    spaceGroup: "P4mm",
    latticeParams: "a ≈ 4.04 Å",
    modulus: "70 GPa",
    poisson: "0.31",
    hardness: "5 Mohs",
    composition: [
      { name: "Pb", value: 40, fill: "#6b7280" },
      { name: "Zr", value: 30, fill: "#9ca3af" },
      { name: "Ti", value: 10, fill: "#cbd5e1" },
      { name: "O", value: 20, fill: "#06b6d4" },
    ],
    morphology: "Ferroelectric domains with grain boundaries.",
    defectAnalysis: "Domain wall motion defects.",
    spectrumShift: 28
  },
  {
    name: "Silicon Dioxide (Fused Silica)",
    crystalSystem: "Amorphous",
    spaceGroup: "—",
    latticeParams: "Non-crystalline",
    modulus: "72 GPa",
    poisson: "0.17",
    hardness: "7 Mohs",
    composition: [
      { name: "Si", value: 47, fill: "#a855f7" },
      { name: "O", value: 53, fill: "#06b6d4" },
    ],
    morphology: "Glassy smooth surface.",
    defectAnalysis: "Minimal structural defects.",
    spectrumShift: 16
  },
  {
    name: "Boron Nitride (h-BN)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 2.50 Å, c = 6.66 Å",
    modulus: "800 GPa",
    poisson: "0.21",
    hardness: "2 Mohs",
    composition: [
      { name: "B", value: 50, fill: "#f59e0b" },
      { name: "N", value: 50, fill: "#06b6d4" },
    ],
    morphology: "Layered sheets similar to graphite.",
    defectAnalysis: "Layer misalignment defects.",
    spectrumShift: 20
  },
  {
    name: "Cubic Boron Nitride (c-BN)",
    crystalSystem: "Cubic",
    spaceGroup: "F-43m",
    latticeParams: "a = 3.61 Å",
    modulus: "900 GPa",
    poisson: "0.10",
    hardness: "9.5 Mohs",
    composition: [
      { name: "B", value: 50, fill: "#f59e0b" },
      { name: "N", value: 50, fill: "#06b6d4" },
    ],
    morphology: "Hard crystalline grains.",
    defectAnalysis: "Minimal defects.",
    spectrumShift: 38
  },
  {
    name: "Yttria-Stabilized Zirconia (YSZ)",
    crystalSystem: "Cubic",
    spaceGroup: "Fm-3m",
    latticeParams: "a ≈ 5.14 Å",
    modulus: "210 GPa",
    poisson: "0.30",
    hardness: "8 Mohs",
    composition: [
      { name: "ZrO2", value: 90, fill: "#9ca3af" },
      { name: "Y2O3", value: 10, fill: "#a855f7" },
    ],
    morphology: "Dense stabilized ceramic structure.",
    defectAnalysis: "Oxygen vacancies enhance conductivity.",
    spectrumShift: 27
  },
  {
    name: "Lanthanum Oxide (La2O3)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P-3m1",
    latticeParams: "a = 3.94 Å",
    modulus: "140 GPa",
    poisson: "0.29",
    hardness: "5 Mohs",
    composition: [
      { name: "La", value: 70, fill: "#9ca3af" },
      { name: "O", value: 30, fill: "#06b6d4" },
    ],
    morphology: "Crystalline oxide grains.",
    defectAnalysis: "Oxygen vacancies present.",
    spectrumShift: 19
  },
  {
    name: "Cerium Oxide (CeO2)",
    crystalSystem: "Cubic",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 5.41 Å",
    modulus: "230 GPa",
    poisson: "0.30",
    hardness: "6 Mohs",
    composition: [
      { name: "Ce", value: 81, fill: "#9ca3af" },
      { name: "O", value: 19, fill: "#06b6d4" },
    ],
    morphology: "Fine oxide nanoparticles.",
    defectAnalysis: "Oxygen vacancies enable redox activity.",
    spectrumShift: 21
  },
  {
    name: "Nickel Oxide (NiO)",
    crystalSystem: "Cubic",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 4.17 Å",
    modulus: "200 GPa",
    poisson: "0.21",
    hardness: "6 Mohs",
    composition: [
      { name: "Ni", value: 79, fill: "#6b7280" },
      { name: "O", value: 21, fill: "#06b6d4" },
    ],
    morphology: "Polycrystalline oxide grains.",
    defectAnalysis: "Cation vacancies present.",
    spectrumShift: 20
  },
  {
    name: "Titanium Dioxide (TiO2 - Rutile)",
    crystalSystem: "Tetragonal",
    spaceGroup: "P4_2/mnm",
    latticeParams: "a = 4.59 Å, c = 2.96 Å",
    modulus: "230 GPa",
    poisson: "0.27",
    hardness: "6–7 Mohs",
    composition: [
      { name: "Ti", value: 60, fill: "#cbd5e1" },
      { name: "O", value: 40, fill: "#06b6d4" },
    ],
    morphology: "Elongated crystalline grains.",
    defectAnalysis: "Oxygen vacancies influence optical properties.",
    spectrumShift: 23
  },
  {
    name: "Tin Oxide (SnO2)",
    crystalSystem: "Tetragonal",
    spaceGroup: "P4_2/mnm",
    latticeParams: "a = 4.74 Å, c = 3.19 Å",
    modulus: "260 GPa",
    poisson: "0.29",
    hardness: "6.5 Mohs",
    composition: [
      { name: "Sn", value: 78, fill: "#9ca3af" },
      { name: "O", value: 22, fill: "#06b6d4" },
    ],
    morphology: "Nanocrystalline grains.",
    defectAnalysis: "Oxygen vacancies enhance conductivity.",
    spectrumShift: 24
  },
  {
    name: "Zinc Sulfide (ZnS)",
    crystalSystem: "Cubic",
    spaceGroup: "F-43m",
    latticeParams: "a = 5.41 Å",
    modulus: "75 GPa",
    poisson: "0.28",
    hardness: "4 Mohs",
    composition: [
      { name: "Zn", value: 50, fill: "#9ca3af" },
      { name: "S", value: 50, fill: "#facc15" },
    ],
    morphology: "Fine crystalline particles.",
    defectAnalysis: "Vacancy defects present.",
    spectrumShift: 17
  },
  {
    name: "Cadmium Telluride (CdTe)",
    crystalSystem: "Cubic",
    spaceGroup: "F-43m",
    latticeParams: "a = 6.48 Å",
    modulus: "52 GPa",
    poisson: "0.41",
    hardness: "3 Mohs",
    composition: [
      { name: "Cd", value: 50, fill: "#9ca3af" },
      { name: "Te", value: 50, fill: "#22c55e" },
    ],
    morphology: "Polycrystalline semiconductor grains.",
    defectAnalysis: "Defect tolerance high.",
    spectrumShift: 29
  },
  {
    name: "Indium Phosphide (InP)",
    crystalSystem: "Cubic",
    spaceGroup: "F-43m",
    latticeParams: "a = 5.87 Å",
    modulus: "71 GPa",
    poisson: "0.36",
    hardness: "5 Mohs",
    composition: [
      { name: "In", value: 50, fill: "#9ca3af" },
      { name: "P", value: 50, fill: "#f59e0b" },
    ],
    morphology: "Smooth semiconductor crystal.",
    defectAnalysis: "Low defect density.",
    spectrumShift: 30
  },
  {
    name: "Aluminum Nitride (AlN)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3mc",
    latticeParams: "a = 3.11 Å, c = 4.98 Å",
    modulus: "308 GPa",
    poisson: "0.21",
    hardness: "8 Mohs",
    composition: [
      { name: "Al", value: 50, fill: "#9ca3af" },
      { name: "N", value: 50, fill: "#06b6d4" },
    ],
    morphology: "Fine ceramic grains with high thermal conductivity.",
    defectAnalysis: "Low defect density.",
    spectrumShift: 26
  },
  {
    name: "Gallium Nitride (GaN)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3mc",
    latticeParams: "a = 3.19 Å, c = 5.19 Å",
    modulus: "300 GPa",
    poisson: "0.23",
    hardness: "6 Mohs",
    composition: [
      { name: "Ga", value: 50, fill: "#9ca3af" },
      { name: "N", value: 50, fill: "#06b6d4" },
    ],
    morphology: "Hexagonal crystal grains with smooth surfaces.",
    defectAnalysis: "Threading dislocations common in thin films.",
    spectrumShift: 31
  },
  {
    name: "Aluminum Gallium Nitride (AlGaN)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3mc",
    latticeParams: "a ≈ 3.11 Å",
    modulus: "280 GPa",
    poisson: "0.25",
    hardness: "6.5 Mohs",
    composition: [
      { name: "Al", value: 40, fill: "#9ca3af" },
      { name: "Ga", value: 30, fill: "#9ca3af" },
      { name: "N", value: 30, fill: "#06b6d4" },
    ],
    morphology: "Epitaxial layers with smooth interfaces.",
    defectAnalysis: "Dislocations due to lattice mismatch.",
    spectrumShift: 33
  },
  {
    name: "Silicon Germanium (SiGe)",
    crystalSystem: "Cubic",
    spaceGroup: "Fd-3m",
    latticeParams: "a ≈ 5.5 Å",
    modulus: "130 GPa",
    poisson: "0.28",
    hardness: "6 Mohs",
    composition: [
      { name: "Si", value: 60, fill: "#a855f7" },
      { name: "Ge", value: 40, fill: "#6b7280" },
    ],
    morphology: "Uniform alloy semiconductor lattice.",
    defectAnalysis: "Strain-induced defects present.",
    spectrumShift: 30
  },
  {
    name: "Cadmium Sulfide (CdS)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3mc",
    latticeParams: "a = 4.14 Å, c = 6.72 Å",
    modulus: "42 GPa",
    poisson: "0.29",
    hardness: "3 Mohs",
    composition: [
      { name: "Cd", value: 50, fill: "#9ca3af" },
      { name: "S", value: 50, fill: "#facc15" },
    ],
    morphology: "Nanocrystalline grains.",
    defectAnalysis: "Sulfur vacancies common.",
    spectrumShift: 27
  },
  {
    name: "Lead Sulfide (PbS)",
    crystalSystem: "Cubic",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 5.93 Å",
    modulus: "70 GPa",
    poisson: "0.28",
    hardness: "2.5 Mohs",
    composition: [
      { name: "Pb", value: 60, fill: "#6b7280" },
      { name: "S", value: 40, fill: "#facc15" },
    ],
    morphology: "Cubic crystalline grains.",
    defectAnalysis: "Vacancy defects influence conductivity.",
    spectrumShift: 26
  },
  {
    name: "Mercury Cadmium Telluride (HgCdTe)",
    crystalSystem: "Cubic",
    spaceGroup: "F-43m",
    latticeParams: "a ≈ 6.46 Å",
    modulus: "50 GPa",
    poisson: "0.40",
    hardness: "2 Mohs",
    composition: [
      { name: "Hg", value: 40, fill: "#9ca3af" },
      { name: "Cd", value: 30, fill: "#9ca3af" },
      { name: "Te", value: 30, fill: "#22c55e" },
    ],
    morphology: "Polycrystalline semiconductor layers.",
    defectAnalysis: "High defect tolerance.",
    spectrumShift: 34
  },
  {
    name: "Indium Gallium Arsenide (InGaAs)",
    crystalSystem: "Cubic",
    spaceGroup: "F-43m",
    latticeParams: "a ≈ 5.87 Å",
    modulus: "68 GPa",
    poisson: "0.35",
    hardness: "5 Mohs",
    composition: [
      { name: "In", value: 40, fill: "#9ca3af" },
      { name: "Ga", value: 20, fill: "#9ca3af" },
      { name: "As", value: 40, fill: "#ef4444" },
    ],
    morphology: "Smooth epitaxial layers.",
    defectAnalysis: "Dislocations due to mismatch.",
    spectrumShift: 32
  },
  {
    name: "Zinc Selenide (ZnSe)",
    crystalSystem: "Cubic",
    spaceGroup: "F-43m",
    latticeParams: "a = 5.67 Å",
    modulus: "67 GPa",
    poisson: "0.28",
    hardness: "4 Mohs",
    composition: [
      { name: "Zn", value: 50, fill: "#9ca3af" },
      { name: "Se", value: 50, fill: "#22c55e" },
    ],
    morphology: "Transparent crystalline grains.",
    defectAnalysis: "Vacancy defects present.",
    spectrumShift: 25
  },
  {
    name: "Copper Oxide (CuO)",
    crystalSystem: "Monoclinic",
    spaceGroup: "C2/c",
    latticeParams: "a = 4.68 Å",
    modulus: "140 GPa",
    poisson: "0.28",
    hardness: "4 Mohs",
    composition: [
      { name: "Cu", value: 80, fill: "#ea580c" },
      { name: "O", value: 20, fill: "#06b6d4" },
    ],
    morphology: "Layered oxide grains.",
    defectAnalysis: "Oxygen vacancies present.",
    spectrumShift: 22
  },
  {
    name: "Iron Sulfide (FeS)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 3.44 Å",
    modulus: "120 GPa",
    poisson: "0.29",
    hardness: "4 Mohs",
    composition: [
      { name: "Fe", value: 60, fill: "#94a3b8" },
      { name: "S", value: 40, fill: "#facc15" },
    ],
    morphology: "Layered sulfide grains.",
    defectAnalysis: "Vacancy defects common.",
    spectrumShift: 20
  },
  {
    name: "Cobalt Oxide (CoO)",
    crystalSystem: "Cubic",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 4.26 Å",
    modulus: "180 GPa",
    poisson: "0.21",
    hardness: "5 Mohs",
    composition: [
      { name: "Co", value: 78, fill: "#6b7280" },
      { name: "O", value: 22, fill: "#06b6d4" },
    ],
    morphology: "Fine oxide grains.",
    defectAnalysis: "Cation vacancies present.",
    spectrumShift: 21
  },
  {
    name: "Manganese Dioxide (MnO2)",
    crystalSystem: "Tetragonal",
    spaceGroup: "P4_2/mnm",
    latticeParams: "a = 4.39 Å",
    modulus: "150 GPa",
    poisson: "0.25",
    hardness: "6 Mohs",
    composition: [
      { name: "Mn", value: 63, fill: "#a855f7" },
      { name: "O", value: 37, fill: "#06b6d4" },
    ],
    morphology: "Nanostructured oxide grains.",
    defectAnalysis: "Oxygen vacancies.",
    spectrumShift: 23
  },
  {
    name: "Nickel Sulfide (NiS)",
    crystalSystem: "Hexagonal",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a = 3.42 Å",
    modulus: "130 GPa",
    poisson: "0.28",
    hardness: "4 Mohs",
    composition: [
      { name: "Ni", value: 65, fill: "#6b7280" },
      { name: "S", value: 35, fill: "#facc15" },
    ],
    morphology: "Layered sulfide grains.",
    defectAnalysis: "Vacancy defects.",
    spectrumShift: 22
  },
  {
    name: "Titanium Nitride (TiN)",
    crystalSystem: "Cubic",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 4.24 Å",
    modulus: "600 GPa",
    poisson: "0.25",
    hardness: "9 Mohs",
    composition: [
      { name: "Ti", value: 50, fill: "#cbd5e1" },
      { name: "N", value: 50, fill: "#06b6d4" },
    ],
    morphology: "Dense golden ceramic coating.",
    defectAnalysis: "Low defect density.",
    spectrumShift: 29
  },
  {
    name: "Chromium Nitride (CrN)",
    crystalSystem: "Cubic",
    spaceGroup: "Fm-3m",
    latticeParams: "a = 4.14 Å",
    modulus: "350 GPa",
    poisson: "0.22",
    hardness: "8 Mohs",
    composition: [
      { name: "Cr", value: 50, fill: "#9ca3af" },
      { name: "N", value: 50, fill: "#06b6d4" },
    ],
    morphology: "Fine ceramic coating grains.",
    defectAnalysis: "Low defect density.",
    spectrumShift: 27
  },
  {
    name: "Aluminum Oxynitride (AlON)",
    crystalSystem: "Cubic",
    spaceGroup: "Fd-3m",
    latticeParams: "a ≈ 7.9 Å",
    modulus: "320 GPa",
    poisson: "0.24",
    hardness: "8 Mohs",
    composition: [
      { name: "Al", value: 50, fill: "#9ca3af" },
      { name: "O", value: 25, fill: "#06b6d4" },
      { name: "N", value: 25, fill: "#06b6d4" },
    ],
    morphology: "Transparent ceramic grains.",
    defectAnalysis: "Low defect density.",
    spectrumShift: 28
  },
  {
    name: "Magnesium Aluminate (MgAl2O4 Spinel)",
    crystalSystem: "Cubic",
    spaceGroup: "Fd-3m",
    latticeParams: "a = 8.08 Å",
    modulus: "200 GPa",
    poisson: "0.26",
    hardness: "8 Mohs",
    composition: [
      { name: "Mg", value: 17, fill: "#d1d5db" },
      { name: "Al", value: 37, fill: "#9ca3af" },
      { name: "O", value: 46, fill: "#06b6d4" },
    ],
    morphology: "Dense ceramic grains.",
    defectAnalysis: "Anti-site defects present.",
    spectrumShift: 22
  },
  {
    name: "Lithium Cobalt Oxide (LiCoO2)",
    crystalSystem: "Hexagonal",
    spaceGroup: "R-3m",
    latticeParams: "a = 2.82 Å, c = 14.05 Å",
    modulus: "150 GPa",
    poisson: "0.30",
    hardness: "5 Mohs",
    composition: [
      { name: "Li", value: 10, fill: "#a855f7" },
      { name: "Co", value: 45, fill: "#6b7280" },
      { name: "O", value: 45, fill: "#06b6d4" },
    ],
    morphology: "Layered battery material structure.",
    defectAnalysis: "Lithium vacancy defects.",
    spectrumShift: 26
  },
  {
    name: "Lithium Iron Phosphate (LiFePO4)",
    crystalSystem: "Orthorhombic",
    spaceGroup: "Pnma",
    latticeParams: "a = 10.33 Å",
    modulus: "140 GPa",
    poisson: "0.29",
    hardness: "5 Mohs",
    composition: [
      { name: "Li", value: 10, fill: "#a855f7" },
      { name: "Fe", value: 30, fill: "#94a3b8" },
      { name: "P", value: 20, fill: "#f59e0b" },
      { name: "O", value: 40, fill: "#06b6d4" },
    ],
    morphology: "Granular battery cathode particles.",
    defectAnalysis: "Lithium diffusion defects.",
    spectrumShift: 25
  },
  {
    name: "Lithium Nickel Manganese Cobalt Oxide (NMC)",
    crystalSystem: "Hexagonal",
    spaceGroup: "R-3m",
    latticeParams: "a ≈ 2.86 Å, c ≈ 14.2 Å",
    modulus: "160 GPa",
    poisson: "0.30",
    hardness: "5 Mohs",
    composition: [
      { name: "Li", value: 7, fill: "#a855f7" },
      { name: "Ni", value: 33, fill: "#6b7280" },
      { name: "Mn", value: 30, fill: "#a855f7" },
      { name: "Co", value: 30, fill: "#6b7280" },
    ],
    morphology: "Layered cathode particles with uniform grain distribution.",
    defectAnalysis: "Cation mixing and lithium vacancies present.",
    spectrumShift: 27
  },
  {
    name: "Lithium Titanate (Li4Ti5O12)",
    crystalSystem: "Cubic",
    spaceGroup: "Fd-3m",
    latticeParams: "a = 8.36 Å",
    modulus: "165 GPa",
    poisson: "0.28",
    hardness: "5 Mohs",
    composition: [
      { name: "Li", value: 20, fill: "#a855f7" },
      { name: "Ti", value: 40, fill: "#cbd5e1" },
      { name: "O", value: 40, fill: "#06b6d4" },
    ],
    morphology: "Fine granular particles with high uniformity.",
    defectAnalysis: "Stable structure with minimal volume change.",
    spectrumShift: 26
  },
  {
    name: "Sodium Ion Cathode (NaMnO2)",
    crystalSystem: "Monoclinic",
    spaceGroup: "C2/m",
    latticeParams: "a ≈ 5.6 Å",
    modulus: "120 GPa",
    poisson: "0.29",
    hardness: "4.5 Mohs",
    composition: [
      { name: "Na", value: 20, fill: "#3b82f6" },
      { name: "Mn", value: 40, fill: "#a855f7" },
      { name: "O", value: 40, fill: "#06b6d4" },
    ],
    morphology: "Layered oxide structure.",
    defectAnalysis: "Sodium vacancy defects.",
    spectrumShift: 23
  },
  {
    name: "Graphene Quantum Dots",
    crystalSystem: "Amorphous/Graphitic",
    spaceGroup: "—",
    latticeParams: "Nanoscale domains",
    modulus: "200 GPa",
    poisson: "0.20",
    hardness: "5 Mohs",
    composition: [
      { name: "C", value: 85, fill: "#3b82f6" },
      { name: "O", value: 15, fill: "#06b6d4" },
    ],
    morphology: "Nano-sized graphitic clusters.",
    defectAnalysis: "Edge defects dominate.",
    spectrumShift: 35
  },
  {
    name: "Black Phosphorus",
    crystalSystem: "Orthorhombic",
    spaceGroup: "Cmca",
    latticeParams: "a = 3.31 Å, b = 10.47 Å",
    modulus: "100 GPa",
    poisson: "0.21",
    hardness: "3 Mohs",
    composition: [
      { name: "P", value: 100, fill: "#f59e0b" },
    ],
    morphology: "Layered puckered sheets.",
    defectAnalysis: "Surface oxidation defects.",
    spectrumShift: 28
  },
  {
    name: "MXene (Ti3C2Tx)",
    crystalSystem: "Layered",
    spaceGroup: "P6_3/mmc",
    latticeParams: "a ≈ 3.05 Å",
    modulus: "330 GPa",
    poisson: "0.25",
    hardness: "6 Mohs",
    composition: [
      { name: "Ti", value: 50, fill: "#cbd5e1" },
      { name: "C", value: 30, fill: "#3b82f6" },
      { name: "Surface Groups", value: 20, fill: "#06b6d4" },
    ],
    morphology: "Layered 2D sheets with surface terminations.",
    defectAnalysis: "Surface functional group defects.",
    spectrumShift: 36
  },
  {
    name: "Aerogel (Silica)",
    crystalSystem: "Amorphous",
    spaceGroup: "—",
    latticeParams: "Highly porous",
    modulus: "0.01 GPa",
    poisson: "0.20",
    hardness: "0.5 Mohs",
    composition: [
      { name: "SiO2", value: 95, fill: "#a855f7" },
      { name: "Air", value: 5, fill: "#06b6d4" },
    ],
    morphology: "Highly porous nano-network.",
    defectAnalysis: "Extreme porosity dominates.",
    spectrumShift: 12
  },
  {
    name: "Metal Organic Framework (MOF-5)",
    crystalSystem: "Cubic",
    spaceGroup: "Fm-3m",
    latticeParams: "a ≈ 25.9 Å",
    modulus: "15 GPa",
    poisson: "0.30",
    hardness: "1 Mohs",
    composition: [
      { name: "Zn", value: 30, fill: "#9ca3af" },
      { name: "Organic", value: 70, fill: "#3b82f6" },
    ],
    morphology: "Highly porous crystalline network.",
    defectAnalysis: "Missing linker defects.",
    spectrumShift: 20
  },
  {
    name: "Perfluoropolyether (PFPE)",
    crystalSystem: "Amorphous",
    spaceGroup: "—",
    latticeParams: "Polymeric chains",
    modulus: "0.05 GPa",
    poisson: "0.45",
    hardness: "0.5 Mohs",
    composition: [
      { name: "C", value: 40, fill: "#3b82f6" },
      { name: "F", value: 60, fill: "#22c55e" },
    ],
    morphology: "Flexible polymer chains.",
    defectAnalysis: "Chain mobility defects.",
    spectrumShift: 6
  },
  {
    name: "Polycarbonate (PC)",
    crystalSystem: "Amorphous",
    spaceGroup: "—",
    latticeParams: "Non-crystalline",
    modulus: "2.5 GPa",
    poisson: "0.37",
    hardness: "2 Mohs",
    composition: [
      { name: "C", value: 75, fill: "#3b82f6" },
      { name: "O", value: 20, fill: "#06b6d4" },
      { name: "H", value: 5, fill: "#22c55e" },
    ],
    morphology: "Glassy polymer matrix.",
    defectAnalysis: "Microvoids and stress cracks.",
    spectrumShift: 9
  },
  {
    name: "ABS Plastic",
    crystalSystem: "Amorphous",
    spaceGroup: "—",
    latticeParams: "Polymer blend",
    modulus: "2 GPa",
    poisson: "0.35",
    hardness: "2 Mohs",
    composition: [
      { name: "C", value: 85, fill: "#3b82f6" },
      { name: "H", value: 10, fill: "#22c55e" },
      { name: "N", value: 5, fill: "#06b6d4" },
    ],
    morphology: "Phase-separated polymer domains.",
    defectAnalysis: "Interfacial defects present.",
    spectrumShift: 8
  },
  {
    name: "Nylon (Polyamide)",
    crystalSystem: "Semi-Crystalline",
    spaceGroup: "—",
    latticeParams: "Chain aligned",
    modulus: "2.7 GPa",
    poisson: "0.39",
    hardness: "2 Mohs",
    composition: [
      { name: "C", value: 65, fill: "#3b82f6" },
      { name: "H", value: 10, fill: "#22c55e" },
      { name: "N", value: 15, fill: "#06b6d4" },
      { name: "O", value: 10, fill: "#06b6d4" },
    ],
    morphology: "Crystalline and amorphous regions.",
    defectAnalysis: "Chain misalignment defects.",
    spectrumShift: 10
  },
  {
    name: "Polyethylene Terephthalate (PET)",
    crystalSystem: "Semi-Crystalline",
    spaceGroup: "—",
    latticeParams: "Polymer chains",
    modulus: "2.8 GPa",
    poisson: "0.38",
    hardness: "2 Mohs",
    composition: [
      { name: "C", value: 70, fill: "#3b82f6" },
      { name: "O", value: 20, fill: "#06b6d4" },
      { name: "H", value: 10, fill: "#22c55e" },
    ],
    morphology: "Semi-crystalline polymer structure.",
    defectAnalysis: "Crystallinity variations.",
    spectrumShift: 9
  },
  {
    name: "Polylactic Acid (PLA)",
    crystalSystem: "Semi-Crystalline",
    spaceGroup: "—",
    latticeParams: "Polymer chains",
    modulus: "3 GPa",
    poisson: "0.36",
    hardness: "2 Mohs",
    composition: [
      { name: "C", value: 50, fill: "#3b82f6" },
      { name: "O", value: 40, fill: "#06b6d4" },
      { name: "H", value: 10, fill: "#22c55e" },
    ],
    morphology: "Biopolymer crystalline regions.",
    defectAnalysis: "Hydrolytic degradation defects.",
    spectrumShift: 11
  },
  {
    name: "Polyurethane (PU)",
    crystalSystem: "Amorphous",
    spaceGroup: "—",
    latticeParams: "Flexible chains",
    modulus: "0.05 GPa",
    poisson: "0.45",
    hardness: "1 Mohs",
    composition: [
      { name: "C", value: 65, fill: "#3b82f6" },
      { name: "O", value: 20, fill: "#06b6d4" },
      { name: "N", value: 10, fill: "#06b6d4" },
      { name: "H", value: 5, fill: "#22c55e" },
    ],
    morphology: "Soft polymer matrix.",
    defectAnalysis: "Phase separation defects.",
    spectrumShift: 7
  },
  {
    name: "Shape Memory Alloy (NiTi)",
    crystalSystem: "Cubic (B2)",
    spaceGroup: "Pm-3m",
    latticeParams: "a ≈ 3.01 Å",
    modulus: "75 GPa",
    poisson: "0.33",
    hardness: "4 Mohs",
    composition: [
      { name: "Ni", value: 50, fill: "#6b7280" },
      { name: "Ti", value: 50, fill: "#cbd5e1" },
    ],
    morphology: "Martensitic transformation structure.",
    defectAnalysis: "Phase transformation defects.",
    spectrumShift: 21
  },
  {
    name: "Superalloy (Co-based)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a ≈ 3.55 Å",
    modulus: "210 GPa",
    poisson: "0.30",
     hardness: "6 Mohs",
    composition: [
      { name: "Co", value: 60, fill: "#6b7280" },
      { name: "Cr", value: 20, fill: "#9ca3af" },
      { name: "W", value: 20, fill: "#6b7280" },
    ],
    morphology: "Precipitate strengthened grains.",
    defectAnalysis: "Carbide and phase defects.",
    spectrumShift: 24
  },
  {
    name: "High Entropy Alloy (FeNiCrCoMn)",
    crystalSystem: "Face-Centered Cubic (FCC)",
    spaceGroup: "Fm-3m",
    latticeParams: "a ≈ 3.59 Å",
    modulus: "200 GPa",
    poisson: "0.32",
    hardness: "5.5 Mohs",
    composition: [
      { name: "Fe", value: 20, fill: "#94a3b8" },
      { name: "Ni", value: 20, fill: "#6b7280" },
      { name: "Cr", value: 20, fill: "#9ca3af" },
      { name: "Co", value: 20, fill: "#6b7280" },
      { name: "Mn", value: 20, fill: "#a855f7" },
    ],
    morphology: "Single-phase solid solution.",
    defectAnalysis: "Severe lattice distortion.",
    spectrumShift: 25
  },
  {
    name: "Bulk Metallic Glass (Zr-based)",
    crystalSystem: "Amorphous",
    spaceGroup: "—",
    latticeParams: "Non-crystalline",
    modulus: "100 GPa",
    poisson: "0.36",
    hardness: "5 Mohs",
    composition: [
      { name: "Zr", value: 60, fill: "#9ca3af" },
      { name: "Cu", value: 20, fill: "#ea580c" },
      { name: "Al", value: 20, fill: "#9ca3af" },
    ],
    morphology: "Glassy metallic structure.",
    defectAnalysis: "Shear band formation.",
    spectrumShift: 22
  }
];

export function getMaterialData(query: string): MaterialStats {
  const norm = query.toLowerCase().trim();

  // Search exact or tight partial matches in the database
  for (const mat of materialDatabase) {
    const matNameNorm = mat.name.toLowerCase();
    
    // Check if the query is in the material name (e.g. "zinc" matches "Zinc (Zn)")
    if (matNameNorm.includes(norm)) {
      return mat;
    }
  }

  // Pure deterministic fallback for entirely unknown entries
  const charCode = query.charCodeAt(0) || 100;
  const isBccFallback = charCode % 2 === 0;

  return {
    name: query || "Unknown Sample X-1A",
    crystalSystem: isBccFallback ? "Body-Centered Cubic (BCC) - Estimated" : "Face-Centered Cubic (FCC) - Estimated",
    spaceGroup: isBccFallback ? "Im-3m" : "Fm-3m",
    latticeParams: isBccFallback ? "a ≈ 3.20 Å" : "a ≈ 4.10 Å",
    modulus: "110 GPa (Estimated)",
    poisson: "0.28",
    hardness: "Unknown (Est. 4.5 Mohs)",
    composition: [
      { name: (query.substring(0,2).toUpperCase() || "El"), value: 65, fill: "#ef4444" },
      { name: "O", value: 20, fill: "#8b5cf6" },
      { name: "C", value: 10, fill: "#3b82f6" },
      { name: "Si", value: 5, fill: "#06b6d4" },
    ],
    morphology: `Analysis of ${query || 'the sample'} reveals a polycrystalline matrix. Granular boundaries are sharp with minimal porosity between metallic/atomic domains. Topographic scan suggests generic lattice construction.`,
    defectAnalysis: "Varying micro-stress boundaries localized near the secondary zones. The dislocation network implies the material has undergone thermal or kinetic stress prior to microscopy gathering.",
    spectrumShift: 20
  };
}
